service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - dynamodb:*
    Resource: "*"

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline
	
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  autoswagger:
    basePath: '/dev'
    apiType: 'http'

functions:
  addProductsToDB:
    handler: handlers/addProductsToDB.handler
    events:
      - http:
          method: GET
          path: init
          cors: true
  getProductsList:
    handler: handlers/getProductsList.handler
    events:
      - http:
          method: GET
          path: products
          cors: true
          description: GET products list
          responses:
            200:
              description: OK
            500:
              description: Internal Server Error
  getProductsById:
    handler: handlers/getProductsById.handler
    events:
      - http:
          method: GET
          path: products/{id}
          cors: true
          description: GET product by ID
          responses:
            200:
              description: OK
            404:
              description: Not Found
            500:
              description: Internal Server Error
  createProduct:
    handler: handlers/createProduct.handler
    events:
      - http:
          method: POST
          path: products
          cors: true
          description: Create new product
          responses:
            200:
              description: OK
            500:
              description: Internal Server Error

resources:
  Resources:
    Products:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1  

    Stocks:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Stocks
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1    